### ISSUE TITLE
Unable to use in netstandard projects

### ISSUE THREAD

**Issue by HenryGarle** [restpackio/restpack-csharp#1]
Currently the projects TargetFramework is set to netcoreapp2.2 which means that usage of the package in anything other than an app targeted project is not possible. The target needs to be changed to netstandard2.0 in order to be usable within other netstandard projects.

**Comment by namirali** [comment]
netstandart version changed to 2.0 and module updated (1.0.2)
Thank you for reporting @HenryGarle

**Comment by HenryGarle** [comment]
Sorry to be a pain but it needs to target netstandard2.0 not netcoreapp2.0, currently it still has the same issue as before. I have submitted a PR with the minor change. Thank you for looking to address it!
