### ISSUE TITLE
Please update to use latest or flexible version of RestSharp

### ISSUE THREAD

**Issue by kinetiq** [restpackio/restpack-csharp#3]
I'm getting: 

FileNotFoundException: Could not load file or assembly 'RestSharp, Version=106.6.9.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. The system cannot find the file specified.

Reverting to that version works, but might be breaking other things. That is many versions behind. The nuget package is set to require >= 106.6.9 but clearly the project itself wants that specific version.

Async methods and MemoryStreams would also be fantastic but that's very secondary. Thanks. :)

**Comment by kinetiq** [comment]
@namirali Checking on this - not sure how a whole month has gone by, but this remains a problem for me. Should be easy to fix as well.

**Comment by kinetiq** [comment]
@namirali Can I please get a reply to this? This is a problem for me, I will have to find a different solution if this isn't being maintained at all. :( Previously someone told me it would be fixed the next day - that was over a month ago.

**Comment by namirali** [comment]
@kinetiq i'm sorry for inconvenience and delay. I've updated RestSharp to latest version (106.10.1), hope that will work for you. Please update the our module to [1.0.4](https://www.nuget.org/packages/Restpack/1.0.4)
