### ISSUE TITLE
Issue in development...

### ISSUE THREAD

**Issue by kinetiq** [restpackio/restpack-csharp#4]
I've started seeing this error intermittently, possibly when I run two conversions within several seconds of each other:

**Exception: Only 1 parallel operations allowed**

Any idea what this is or what to do about it?

Here's the dump:

Restpack.Pdf2Html.Pdf2Html.ExecuteBytes(RequestOptions options)
Restpack.Pdf2Html.Pdf2Html.ConvertHTMLBytes(string html, RequestOptions options)
Keystone.Logic.Services.Survey360.PDFs.PdfService.RenderHtmlAsPdf(string html) in PdfService.cs
+
            var captureResult = Pdf2Html.ConvertHTMLBytes(html, options);
Keystone.Web.Controllers.Report360Condensed.Report360CondensedController.GetFileStreamResult(RootVM model, string html) in Report360CondensedController.cs
+
            var stream = await PdfService.RenderHtmlAsPdf(html);
Keystone.Web.Controllers.Report360Condensed.Report360CondensedController.GetPdf(int id, bool forceRegenerate) in Report360CondensedController.cs
+
            return await GetFileStreamResult(model, html);
lambda_method(Closure , object )
Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable+Awaiter.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by namirali** [comment]
Hello @kinetiq , on free trial only 1 parallel operations allowed. you can upgrade your plan and get upto 30 parallel conversations

**Comment by kinetiq** [comment]
Ok great, I was hoping you would say something like that.
