### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by kinetiq** [restpackio/restpack-csharp#5]
Hey, I could use async support. If I do a pull request with some basic async support, will you accept it? 

Thanks!

**Comment by namirali** [comment]
any improvements are welcomed @kinetiq

**Comment by kinetiq** [comment]
@namirali  Hey, I am working on this, but I see some issues that give me pause.

In the latest version you released for me (thanks for that!), the namespace was changed from Pdf2Html to Html2Pdf. That is more correct and seems reasonable, however I do not see that change in this repo.  

In fact, the last change logged in github was 8 months ago. That makes me think someone is working from a different repo (locally, etc...) and changes are not being checked in here. 

FYI, the name change also breaks your documentation in some places.

Finally, there is no solution file here. That means any time I save, it's going to prompt me to create one, and what gets created may be out of sync with what you are using.

Any chance you can look into these issues? Unless I'm mistaken, they will prevent anyone from contributing without creating additional work for you.
